### PR TITLE
modified print function call for add_book, change_read functions to c…

### PR DESCRIPTION
**Pull request by Hockeydan25**
issue #17 PR to review changes to print statements. @chrismon88 please program is still printing well add_ book and book_change.

### CODE REVIEW

**Comment by claraj** [comment]
Looks good to me!

**Comment by Hockeydan25** [comment]
@chrismon88  looked at code and tested. we could ass \n for easier read.

**Comment by chrismon88** [comment]
@Hockeydan25 tested your changes looks great.

**Comment by Hockeydan25** [comment]
@claraj @chrismon88 issue is now completed and merge, PR #20 successful. closing issue.

**Pull request merged**
