### PR TITLE
removed extras that were not pertaining to the original issue

### PR DESCRIPTION
**Pull request by chrismon88**
@Hockeydan25 re pushed case_sensitive removed extras that weren't significant to original issue.

### CODE REVIEW

**Comment by claraj** [comment]
Remind me, which is the "original issue" ?

**Comment by chrismon88** [comment]
Allowing program to accept both lowercase and uppercase “q” as input for quit menu.
________________________________

**Comment by Hockeydan25** [comment]
@chrismon88 @claraj pulled latest version and this is testing well still.  I think you change the exception BookError:? and put that back to original code? #13

**Comment by chrismon88** [comment]
@Hockeydan25 thanks for testing issue, closing issue and merged.

**Pull request merged**
